{"target_node": "PetAdoptionStatusUpdater/prod_AWS::ApiGateway::Stage", "root_cause_node": "invalid_AWS::DynamoDB::Table", "issue_type": "latency", "severity": 0.12455237500118363, "affected_column": "latency_p50", "timestamp": "2024-05-30 04:28:40.239644", "paths": ["PetAdoptionStatusUpdater/prod_AWS::ApiGateway::Stage", "lambdastatusupdater_AWS::Lambda", "lambdastatusupdater_AWS::Lambda::Function", "invalid_AWS::DynamoDB::Table"]}